version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Library.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=library_db;User Id=postgres;Password=yourpassword;
    depends_on:
      - postgres
      - redis
    networks:
      - library_network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - library_network

networks:
  library_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
