name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Library-Management-System.sln  # Specify your solution file here
    - name: Build
      run: dotnet build Library-Management-System.sln --no-restore  # Specify your solution file here
    - name: Test
      run: dotnet test Library-Management-System.sln --no-build --verbosity normal  # Specify your solution file here
